#!/bin/sh
# /etc/init.d/boinc
# Start/stop/restart

# To do
# - Have a "boinc status" option - not sure what to have as output, though.
# - Have a "boinc logrotate" option for logrotate
# - Have a PID in /var/run/ with trap INT escapes, though, for crashes

BOINC_LOG="/var/log/boinc.log"
BOINC_PATH="/opt/BOINC"
SETI_ACCOUNT="d14af2375aa9c85dd1251f0f04d09654"

boinc_start() {
    if [ -x "${BOINC_PATH}/run_client" ]; then
        echo -n "Starting BOINC..."
        ${BOINC_PATH}/boinc -no_gui_rpc >> ${BOINC_LOG} &
        echo "[OK]"
    else
        echo "[FAIL] cannot find ${BOINC_PATH}/boinc. Exiting." | tee -a ${BOINC_LOG}
        exit 1
    fi
}
boinc_attach(){
    echo -e "Starting BOINC with Grig's account attached (first run)..."
    ${BOINC_PATH}/boinc -no_gui_rpc -attach_project http://setiathome.berkeley.edu ${SETI_ACCOUNT} > ${BOINC_LOG} &
    
}
boinc_stop() {
    echo -n "Stopping BOINC..."
    killall boinc
    if [ $? == "0"]
    then
        echo "[OK]"
        echo "Boinc stopped manually by user $0" >> ${BOINC_LOG}
    else
        echo "[FAIL]"
        echo "Boinc stop attempt made, but either boinc is not running or cannot be stopped $0" >> ${BOINC_LOG}
    fi 
}
boinc_restart() {
    boinc_stop
    sleep 3
    boinc_start
}

case "$1" in
    'start')
        boinc_start
          ;;
    'stop')
        boinc_stop
          ;;
    'restart')
        boinc_restart
          ;;
    'attach')
        boinc_attach
          ;;
    *)
          echo "$0 start|stop|restart|attach" 
esac
exit 0
