#!/bin/sh
# /etc/init.d/boinc
# Start/stop/restart

# To do
# - Have a "boinc status" option - not sure what to have as output, though.
# - Have a "boinc logrotate" option for logrotate
# - Have a PID in /var/run/ with trap INT escapes, though, for crashes

BOINC_LOG="/var/log/boinc.log"
BOINC_PATH="/opt/BOINC"

boinc_start() {
    if [ -x "${BOINC_PATH}/run_client" ]; then
        echo -n "Starting BOINC..."
        ${BOINC_PATH}/run_client --allow_remote_gui_rpc >> ${BOINC_LOG} &
        echo -e "\e[32;1m[OK]\e[m"
    else
        echo -e "\e[32;1m[FAIL]\e[m: cannot find ${BOINC_PATH}/run_client. Exiting." | tee -a ${BOINC_LOG}
        exit 1
    fi
}
boinc_attach(){
    echo -e "Starting BOINC with Grig's account attached (first run)..."
    ${BOINC_PATH}/boinc -no_gui_rpc -attach_project http://setiathome.berkeley.edu d14af2375aa9c85dd1251f0f04d09654 > ${BOINC_LOG} &
    
}
boinc_stop() {
    echo -n "Stopping BOINC..."
    killall boinc
    if [ $? == "0"]
    then
        echo -e "\e[32;1m[OK]\e[m"
        echo "Boinc stopped manually by user $0" >> ${BOINC_LOG}
    else
        echo -e "\e[31;1m[FAIL]\e[m"
        echo "Boinc stop attempt made, but either boinc is not running or cannot be stopped $0" >> ${BOINC_LOG}
    fi 
}
boinc_restart() {
    boinc_stop
    sleep 3
    boinc_start
}
# I commented this out because the "exit_when_idle" seems to have been disabled due to user abuse
#   but I want to keep it here in case I am wrong.
# boinc_drain() {
#    boinc_stop
#    sleep 3
#    echo "Starting BOINC but will exit when all work units are complete..."
#    echo "BOINC restarted with exit_when_idle mode.  Will exit upon completion of work units." | tee -a ${BOINC_LOG}
#    ${BOINC_PATH}/run_client --exit_when_idle --allow_remote_gui_rpc >> ${BOINC_LOG}  &
#}

case "$1" in
    'start')
        boinc_start
          ;;
    'stop')
        boinc_stop
          ;;
    'restart')
        boinc_restart
          ;;
    'attach')
        boinc_attach
          ;;
#    'drain')
#        boinc_drain
#          ;;
    *)
          echo "$0 start|stop|restart|attach" 
esac
exit 0
